INSERT INTO `city` (`id`, `title_en`, `title_ru`) VALUES
(1, 'Tbilisi', 'Тбилиси'),
(2, 'Abasha', 'Абаша'),
(3, 'Ambrolauri', 'Амбролаури'),
(4, 'Akhalkalaki', 'Ахалкалаки'),
(5, 'Akhaltsikhe', 'Ахалцихе'),
(6, 'Akhmeta', 'Ахмета'),
(7, 'Batumi', 'Батуми'),
(8, 'Baghdati', 'Багдати'),
(9, 'Bolnisi', 'Болниси'),
(10, 'Borjomi', 'Боржоми'),
(11, 'Gardabani', 'Гардабани'),
(12, 'Gori', 'Гори'),
(13, 'Gurjaani', 'Гурджаани'),
(14, 'Dedoplistskaro', 'Дедоплисцкаро'),
(15, 'Dmanisi', 'Дманиси'),
(16, 'Dusheti', 'Душети'),
(17, 'Vale', 'Вале'),
(18, 'Vani', 'Вани'),
(19, 'Zestaponi', 'Зестафони'),
(20, 'Zugdidi', 'Зугдиди'),
(21, 'Tetritskaro', 'Тетрицкаро'),
(22, 'Telavi', 'Телави'),
(23, 'Terjola', 'Терджола'),
(24, 'Kaspi', 'Каспи'),
(25, 'Lagodekhi', 'Лагодехи'),
(26, 'Lanchkhuti', 'Ланчхути'),
(27, 'Marneuli', 'Марнеули'),
(28, 'Martvili', 'Мартвили'),
(29, 'Mtskheta', 'Мцхета'),
(30, 'Ninotsminda', 'Ниноцминда'),
(31, 'Ozurgeti', 'Озургети'),
(32, 'Oni', 'Они'),
(33, 'Rustavi', 'Рустави'),
(34, 'Sagarejo', 'Сагареджо'),
(35, 'Samtredia', 'Самтредия'),
(36, 'Sachkhere', 'Сачхере'),
(37, 'Senaki', 'Сенаки'),
(38, 'Sighnaghi', 'Сигнахи'),
(39, 'Tkibuli', 'Ткибули'),
(40, 'Poti', 'Поти'),
(41, 'Kareli', 'Карели'),
(42, 'Kobuleti', 'Кобулети'),
(43, 'Kutaisi', 'Кутаиси'),
(44, 'Kvareli', 'Кварели'),
(45, 'Tsageri', 'Цагери'),
(46, 'Tsalenjikha', 'Цаленджиха'),
(47, 'Tsalka', 'Цалка'),
(48, 'Tsnori', 'Цнори'),
(49, 'Tskaltubo', 'Цхалтубо'),
(50, 'Chiatura', 'Чиатура'),
(51, 'Khashuri', 'Хашури'),
(52, 'Khobi', 'Хоби'),
(53, 'Khoni', 'Хони'),
(54, 'Jvari', 'Джвари');

INSERT INTO `contact` (`id`, `description`, `path`, `data`) VALUES
(1, NULL, 'MobileNumber', '593-47-40-04'),
(2, NULL, 'Facebook', 'https://www.facebook.com/misho.janiashvili'),
(3, NULL, 'Skype', 'mishojaniashvili'),
(4, NULL, 'Email', 'info@tourapp.ge'),
(5, NULL, 'Gmap', '{"lat":"41.7232166","lng":"44.7504341"}'),
(6, NULL, 'Address', 'Ateni Str. 6/8 Apt.25');


INSERT INTO `role` (`id`, `date_created`, `name`) VALUES
(1, '2017-04-23 09:26:12', 'USER'),
(2, '2017-04-23 09:26:12', 'ADMIN');
